name: Image Optimize

on:
  workflow_dispatch:

jobs:
  image-optimize:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
      - name: Installing Dependencies
        run: |
          pip install Pillow
          pip install image
      - name: Downloading Script
        run: curl https://raw.githubusercontent.com/harshau007/automation-scripts/main/image-convert.py -o image-convert.py
      - name: Changing image Format
        run: python3 image-convert.py
      - name: Removing Script
        run: rm -rf image-convert.py
      - name: create pull request
        run: |
          git config --global user.name "Github Action[Bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Optimized Images"
          git push
          
